version: '3.8'

services:
  backend:
    # Points to your specific backend folder
    build: ./back-end-redbus
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/redbus_db
    depends_on:
      - mongodb

  frontend:
    # Points to your specific frontend folder
    build: ./front-end-redbus
    ports:
      - "3000:80"
    stdin_open: true 
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb_redbus
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: