apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: redbus-prod
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb-service:27017/redbus"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: redbus-prod
type: Opaque
data:
  STRIPE_KEY: bXktc2VjcmV0LXZhbHVl
  GOOGLE_CLIENT_ID: bXktZ29vZ2xlLWlk
