apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: redbus-prod
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 200m
